# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Caleb Koch
tagline:          A human
description:      Relevant Links
url:              
#baseurl:         

author:
  name:           'Caleb Koch'
  url:            

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           
