# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Caleb Koch
tagline:          A human
description:      Stuff about me
url:              https://github.com/
#baseurl:          /

author:
  name:           'Caleb Koch'
  url:            https://mywebsite

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/mygithub
