# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Caleb Koch
tagline:          A human
description:      Programmer, student, hobbyist, researcher
url:              cakoch10.github.io
baseurl:          /

author:
  name:           'Caleb Koch'
  url:

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/cakoch10/cakoch10.github.io
